Repository osallak/SpinShot, pull requests merged in 2023-10, with the labels that each got.

#60 REFACTOR: moving swagger code to a separate files
  src/auth/auth.controller.ts
  src/auth/swagger/auth.swagger.ts
  src/friends/friends.controller.ts
  src/friends/guards/friends.guard.ts
  src/friends/swagger/friends.swagger.ts
  src/media/media.controller.ts
  src/media/swagger/media.swagger.ts
  src/user/controller/user.controller.ts
  src/user/swagger/user.swagger.ts
Labels: documentation

#63 Fix/get all friends error
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/guards/42-auth.guard.ts
  src/auth/strategies/jwt.stategy.ts
  src/auth/strategies/local.strategy.ts
  src/friends/dto/pagination.dto.ts
  src/friends/friends.controller.ts
  src/friends/friends.module.ts
  src/friends/friends.service.ts
  src/friends/guards/friends.guard.ts
  src/global/constants/global.constants.ts
  src/main.ts
  src/media/media.controller.ts
  src/media/media.module.ts
  src/prisma-client-exception/prisma-client-exception.filter.ts
  src/storage/storage.service.ts
  src/user/controller/user.controller.ts
  src/user/dto/create-user.dto.ts
  src/user/dto/search.dto.ts
  src/user/dto/update-user.dto.ts
  src/user/helpers/serialize.user.helper.ts
  src/user/swagger/user.swagger.ts
  src/user/user.module.ts
  src/user/user.service.ts
Labels: bug, backend

#64 `chor`: you can now get friends without user
  src/auth/dto/FortyTwo.dto.ts
  src/auth/dto/create-user.dto.ts
  src/friends/friends.service.ts
  src/main.ts
  src/prisma/seed.ts
  src/user/user.controller.ts
Labels: backend

#73 chor: you can search only by username
  src/user/swagger/user.swagger.ts
  src/user/user.service.ts
Labels: backend

#83 using prisma exception filter
  src/main.ts
Labels: bug, backend

#103 Feat/game backend
  .gitignore
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app.module.ts
  src/auth/auth.service.ts
  src/friends/friends.service.ts
  src/games/dto/game-options.dto.ts
  src/games/dto/map-selection.dto.ts
  src/games/dto/move.dto.ts
  src/games/filter/ws.filter.ts
  src/games/games.controller.ts
  src/games/games.gateway.ts
  src/games/games.module.ts
  src/games/games.repository.ts
  src/games/games.service.ts
  src/games/guard/ws.guard.ts
  src/games/helpers/index.ts
  src/games/helpers/pong.helper.ts
  src/games/middleware/ws.mw.ts
  src/games/pong/pong.engine.ts
  src/games/pong/pong.settings.ts
  src/games/types/map-enum.type.ts
  src/games/types/walls-position.enum.ts
  src/global/constants/global.constants.ts
  src/global/dto/pagination-query.dto.ts
  src/media/media.controller.ts
  src/prisma-client-exception/prisma-client-exception.filter.ts
  src/prisma/prisma.service.ts
  src/prisma/seed.ts
  src/user/dto/verify-password.dto.ts
  src/user/helpers/serialize.user.helper.ts
  src/user/user.controller.ts
  src/user/user.module.ts
  src/user/user.service.ts
  tsconfig.tsbuildinfo
Labels: backend

#104 Feat/game backend
  src/games/games.gateway.ts
  src/games/games.repository.ts
  src/games/games.service.ts
  src/games/pong/pong.engine.ts
  src/room/room.controller.ts
  src/user/controller/user.controller.ts
  src/user/helpers/serialize.user.helper.ts
  src/user/user.service.ts
Labels: bug, backend

#102 frontend of chat
  package-lock.json
  package.json
  public/adminIcon.svg
  public/banIcon.svg
  public/invite.svg
  public/kickIcon.svg
  public/muteIcon.svg
  public/threePointforPeridot.svg
  public/timeMute.svg
  src/Components/LandingPage/landingPage.tsx
  src/Components/authentication/signin/signin.tsx
  src/Components/chatPage/channelSettings.tsx
  src/Components/chatPage/channels.tsx
  src/Components/chatPage/channelsStatus/subModal.tsx
  src/Components/chatPage/chatPage.tsx
  src/Components/chatPage/conversationChannel.tsx
  src/Components/chatPage/conversationIndividual.tsx
  src/Components/chatPage/createChannels.tsx
  src/Components/chatPage/exploreChannels.tsx
  src/Components/chatPage/individual.tsx
  src/Components/chatPage/inviteFriends.tsx
  src/Components/chatPage/mobileSubSideBar.tsx
  src/Components/chatPage/subSideBar.tsx
  src/Components/chatPage/subUsersList.tsx
  src/Components/chatPage/usersList.tsx
  src/Components/context/recoilContext.ts
  src/Components/context/recoilContextChannel.ts
  src/Components/context/recoilContextIndividual.ts
  src/Components/friends/currentFriends.tsx
  src/Components/ui/Buttons/SwitchButton.tsx
  src/Components/ui/Buttons/iconButton.tsx
  src/Components/ui/FolderDropDown/DropDownChannel.tsx
  src/Components/ui/FolderDropDown/Dropdown.tsx
  src/Components/ui/FolderDropDown/currentFriendsDropDown.tsx
  src/Components/ui/FolderNavbar/navBar.tsx
  src/Components/ui/Inputs/searchInput.tsx
  src/Components/ui/folderSidebar/mobileSideBar.tsx
  src/Components/ui/folderSidebar/sideBar.tsx
  src/pages/messages/[id].tsx
  src/types/channelConversationType.tsx
  src/types/channelTypes.tsx
  src/types/iMsgDataTypes.tsx
  src/types/individulaTypes.tsx
  src/types/messagesArrays.tsx
  src/types/profileTypes.tsx
  src/utils/dropDownContent.tsx
Labels: frontend

#107 Fixed/lastof chat
  src/Components/chatPage/channelSettings.tsx
  src/Components/chatPage/channelsStatus/subModal.tsx
  src/Components/chatPage/conversationChannel.tsx
  src/Components/chatPage/conversationIndividual.tsx
  src/Components/chatPage/createChannels.tsx
  src/Components/chatPage/exploreChannels.tsx
  src/Components/chatPage/individual.tsx
  src/Components/chatPage/inviteFriends.tsx
  src/Components/chatPage/mobileSubSideBar.tsx
  src/Components/chatPage/subSideBar.tsx
  src/Components/chatPage/subUsersList.tsx
  src/Components/friends/contentFriendsRequest.tsx
  src/Components/friends/contentMyFriends.tsx
  src/Components/friends/currentFriends.tsx
  src/Components/friends/friendRequest.tsx
  src/Components/friends/friends.tsx
  src/Components/ui/FolderDropDown/DropDownChannel.tsx
  src/Components/ui/FolderNavbar/navBar.tsx
  src/Components/ui/folderSidebar/mobileSideBar.tsx
  src/Components/ui/folderSidebar/sideBar.tsx
Labels: frontend

#108 fixed: the issues of friends page
  src/Components/friends/contentMyFriends.tsx
  src/Components/friends/currentFriends.tsx
  src/Components/friends/friendRequest.tsx
  src/Components/friends/friends.tsx
  src/Components/friends/mobileFriends.tsx
Labels: frontend

#114 Fix/conversation chat
  src/Components/authentication/signin/signin.tsx
  src/Components/chatPage/channels.tsx
  src/Components/chatPage/chatPage.tsx
  src/Components/chatPage/conversationChannel.tsx
  src/Components/chatPage/conversationIndividual.tsx
  src/Components/chatPage/individual.tsx
  src/Components/chatPage/mobileSubSideBar.tsx
  src/Components/chatPage/subSideBar.tsx
  src/Components/context/recoilContextChannel.ts
  src/Components/context/recoilContextIndividual.ts
  src/Components/ui/folderSidebar/mobileSideBar.tsx
  src/Components/ui/folderSidebar/sideBar.tsx
  src/types/iMsgDataTypes.tsx
  src/types/individualConversationType.tsx
  src/types/individualTypes.tsx
Labels: frontend

#117 authentication
  src/Components/authentication/signin/signin.tsx
  src/Components/authentication/signup/signup.tsx
  src/Components/ui/Inputs/confirmationPassword.tsx
  src/Components/ui/Inputs/inputBorder.tsx
  src/types/InputsProps.tsx
Labels: frontend

#128 fixed: some issues
  src/Components/authentication/signin/signin.tsx
  src/Components/friends/contentFriendsRequest.tsx
  src/Components/friends/contentMyFriends.tsx
  src/Components/twoFactorAuthentication/twofa.tsx
  src/Components/ui/FolderDropDown/friendsRequestsDropDown.tsx
  src/Components/ui/folderSidebar/sideBar.tsx
Labels: frontend

#127 Fix/statusof user
  public/404.svg
  src/Components/LandingPage/landingPage.tsx
  src/Components/authentication/signin/signin.tsx
  src/Components/authentication/signup/signup.tsx
  src/Components/chatPage/chatPage.tsx
  src/Components/chatPage/conversationIndividual.tsx
  src/Components/chatPage/createChannels.tsx
  src/Components/ui/FolderDropDown/currentFriendsDropDown.tsx
  src/Components/ui/FolderNavbar/navBar.tsx
  src/pages/404.tsx
  src/utils/endPoint.tsx
Labels: frontend

#129 fixed: join to a protected channel
  src/Components/.DS_Store
  src/Components/chatPage/channelSettings.tsx
  src/Components/chatPage/channelsStatus/subModal.tsx
  src/Components/ui/.DS_Store
  src/pages/messages/[id].tsx
  src/pages/profile/[id].tsx
Labels: frontend

#133 feat: signout for 2fa
  src/Components/chatPage/chatPage.tsx
  src/Components/profile/level.tsx
  src/Components/ui/FolderDropDown/DropdownUser.tsx
  src/utils/endPoint.tsx
Labels: frontend

#137 chor: minor changes
  src/auth/auth.controller.ts
  src/user/user.service.ts
Labels: backend
