Repository osallak/SpinShot, pull requests merged in 2023-07, with the labels that each got.

#15 Revert "Feat/components button"
  .eslintrc.json
  .gitignore
  README.md
  next.config.js
  package-lock.json
  package.json
  postcss.config.js
  public/CreateChannel.svg
  public/Email.svg
  public/ExportChannels.svg
  public/Intra.svg
  public/active.svg
  public/unactive.svg
  src/Components/ui/Buttons/AcceptRejectButton.tsx
  src/Components/ui/Buttons/ContinueWithIntra.tsx
  src/Components/ui/Buttons/EmptyButton.tsx
  src/Components/ui/Buttons/IconButton.tsx
  src/Components/ui/Buttons/SimpleButton.tsx
  src/Components/ui/Buttons/SwitchButton.tsx
  src/Components/ui/Buttons/ToggleButton.tsx
  src/pages/SignIn.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/globals.css
  src/types/ButtonProps.tsx
  tailwind.config.js
  tsconfig.json
Labels: help wanted

#18 17 components of button
  .eslintrc.json
  .gitignore
  next.config.js
  package-lock.json
  package.json
  postcss.config.js
  public/CreateChannel.svg
  public/Email.svg
  public/ExportChannels.svg
  public/Intra.svg
  public/active.svg
  public/unactive.svg
  src/Components/ui/Buttons/AcceptRejectButton.tsx
  src/Components/ui/Buttons/ContinueWithIntra.tsx
  src/Components/ui/Buttons/EmptyButton.tsx
  src/Components/ui/Buttons/IconButton.tsx
  src/Components/ui/Buttons/SimpleButton.tsx
  src/Components/ui/Buttons/SwitchButton.tsx
  src/Components/ui/Buttons/ToggleButton.tsx
  src/pages/SignIn.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/globals.css
  src/types/ButtonProps.tsx
  tailwind.config.js
  tsconfig.json
Labels: frontend

#25 Config, for environments separation
  .gitignore
  env/.gitkeep
  env/development.example.env
  package-lock.json
  package.json
  src/app.module.ts
  src/config/configuration.ts
  src/config/validation.ts
  src/main.ts
Labels: backend

#27 `chor:` enable logging (all levels)
  .gitignore
  src/main.ts
Labels: enhancement

#22 17 components of button
  package-lock.json
  package.json
  public/eye-slash.svg
  public/eye.svg
  public/lock.svg
  public/redemail.svg
  public/redeye-slash.svg
  public/redeye.svg
  public/redlock.svg
  public/reduser.svg
  public/user.svg
  src/Components/ui/Buttons/AcceptRejectButton.tsx
  src/Components/ui/Buttons/ContinueWithIntra.tsx
  src/Components/ui/Buttons/EmptyButton.tsx
  src/Components/ui/Buttons/IconButton.tsx
  src/Components/ui/Buttons/PasswordButton.tsx
  src/Components/ui/Buttons/SimpleButton.tsx
  src/Components/ui/Buttons/SwitchButton.tsx
  src/Components/ui/Buttons/ToggleButton.tsx
  src/Components/ui/Inputs/InputBorder.tsx
  src/pages/index.tsx
  src/styles/globals.css
  src/types/ButtonProps.tsx
  src/types/InputsProps.tsx
  tailwind.config.js
Labels: frontend
